    /*localhost:8081/oauth/token?client_id=star&client_secret=starAway&grant_type=password&username={"account":"2064989403","authType":"password","password":"030321liuxinyu"}*/


### 密码模式
POST localhost:9100/service-user/oauth/token?client_id=cross-end&client_secret=030321liuxinyu&grant_type=password&username={"account":"2064989403","authType":"password","password":"030321liuxinyu"}


### token检验
POST localhost:9100/service-user/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiY3Jvc3MtZW5kIl0sInVzZXJfbmFtZSI6IntcImlkXCI6MjAyMTExMjAwNTMsXCJwaG9uZVwiOlwiMTM2NDg4MzcwOTNcIixcImVtYWlsXCI6XCIyMDY0OTg5NDAzQHFxLmNvbVwiLFwiYWNjb3VudFwiOlwiMjA2NDk4OTQwM1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODE0MDM3NTAsImF1dGhvcml0aWVzIjpbIueVmeiogCIsInByb3ZlcmJz5p2D6ZmQIiwiY2hhdCIsIuWPkeihqOaWh-eroCIsIuWPkeihqOivhOiuuiJdLCJqdGkiOiI5MmM4OTdkZS1iN2Q1LTRhZmItOTNmMi0wYjMyZGJlN2ZjNjkiLCJjbGllbnRfaWQiOiJjcm9zcy1lbmQifQ.fhDBFwdMc5lSd7ExhsX6IFPTHUvzPKN_yoJpKLWjMF0





### 资源访问检验
GET localhost:8089/content/777
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiY3Jvc3MtZW5kIl0sInVzZXJfbmFtZSI6IntcImlkXCI6MjAyMTExMjAwNTMsXCJwaG9uZVwiOlwiMTM2NDg4MzcwOTNcIixcImVtYWlsXCI6XCIyMDY0OTg5NDAzQHFxLmNvbVwiLFwiYWNjb3VudFwiOlwiMjA2NDk4OTQwM1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODE0MTQ0NzEsImF1dGhvcml0aWVzIjpbIueVmeiogCIsInByb3ZlcmJz5p2D6ZmQIiwiY2hhdCIsIuWPkeihqOaWh-eroCIsIuWPkeihqOivhOiuuiJdLCJqdGkiOiI2NmJiNzRhOS02NDk3LTQxNWUtOTQxNy1kMzc4ZDRiM2RkYjciLCJjbGllbnRfaWQiOiJjcm9zcy1lbmQifQ._wu-Cv9IVJBP7vDhEfTqOePPuHDxTxVl89T_X879gW4


### 资源访问检验
GET localhost:8083/information/777
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiY3Jvc3MtZW5kIl0sInVzZXJfbmFtZSI6IntcImlkXCI6MjAyMTExMjAwNTMsXCJwaG9uZVwiOlwiMTM2NDg4MzcwOTNcIixcImVtYWlsXCI6XCIyMDY0OTg5NDAzQHFxLmNvbVwiLFwiYWNjb3VudFwiOlwiMjA2NDk4OTQwM1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2ODE0MDY4MzMsImF1dGhvcml0aWVzIjpbIueVmeiogCIsInByb3ZlcmJz5p2D6ZmQIiwiY2hhdCIsIuWPkeihqOaWh-eroCIsIuWPkeihqOivhOiuuiJdLCJqdGkiOiIzNjgwYTM3Ny04MWJhLTRhYjAtOWMwMi1jYTIxN2Y3MjA1NDIiLCJjbGllbnRfaWQiOiJjcm9zcy1lbmQifQ.P3zPcSw-sM-cj4UtcwkPl_qvSBp_pGA2mR2q99mKR7E


### 密码模式实测
POST localhost:9000/service-user/oauth/token?client_id=cross-end&client_secret=cross-end&grant_type=password&username={"email":"2064989403@qq.com","authType":"password","password":"030321liuxinyu"}
