    /*localhost:8081/oauth/token?client_id=star&client_secret=starAway&grant_type=password&username={"account":"2064989403","authType":"password","password":"030321liuxinyu"}*/


### 密码模式
POST localhost:9000/oauth/token?client_id=starBlog&client_secret=030321liuxinyu&grant_type=password&username={"account":"2064989403","authType":"password","password":"030321"}


### token检验
POST localhost:8081/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3RhckJsb2ciXSwidXNlcl9uYW1lIjoie1wiaWRcIjoxNjE2NTE2MTY1LFwicGhvbmVcIjpcIjEzNjQ4ODM3MDkzXCIsXCJFbWFpbFwiOlwiMjA2NDk4OTQwM0BxcS5jb21cIixcImFjY291bnRcIjpcIjIwNjQ5ODk0MDNcIn0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc1MjY5NDMyLCJhdXRob3JpdGllcyI6WyJ0ZXN0Il0sImp0aSI6IjA4MGUyMmIwLTI1ZDEtNDhmMy1iZjYyLTJkZGY0YmU2YmMyYSIsImNsaWVudF9pZCI6InN0YXJCbG9nIn0.cXCb3G4pQszBly_xox4t4BSke_8yEXESeJibJTMpMyM

### 资源访问检验
GET localhost:8089/content/777
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3RhckJsb2ciXSwidXNlcl9uYW1lIjoie1wiaWRcIjoyMDIxMTEyMDA1MyxcInBob25lXCI6XCIxMzY0ODgzNzA5M1wiLFwiRW1haWxcIjpcIjIwNjQ5ODk0MDNAcXEuY29tXCIsXCJhY2NvdW50XCI6XCIyMDY0OTg5NDAzXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY3NTc1NzcwMSwiYXV0aG9yaXRpZXMiOlsi55WZ6KiAIiwicHJvdmVyYnPmnYPpmZAiLCJjaGF0Iiwi5Y-R6KGo5paH56ugIiwi5Y-R6KGo6K-E6K66Il0sImp0aSI6ImQ1ODM5OWFjLTI4OTEtNGE0ZC1hNThjLWQwZjNmN2JlNmRiNSIsImNsaWVudF9pZCI6InN0YXJCbG9nIn0.6PbINedMrvMUumPb5nvT0dzpzXr8fB86tENzsb8cT38

### 资源访问检验
GET localhost:8083/information/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3RhckJsb2ciXSwidXNlcl9uYW1lIjoie1wiaWRcIjoyMDIxMTEyMDA1MyxcInBob25lXCI6XCIxMzY0ODgzNzA5M1wiLFwiRW1haWxcIjpcIjIwNjQ5ODk0MDNAcXEuY29tXCIsXCJhY2NvdW50XCI6XCIyMDY0OTg5NDAzXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY3NTc1NzcwMSwiYXV0aG9yaXRpZXMiOlsi55WZ6KiAIiwicHJvdmVyYnPmnYPpmZAiLCJjaGF0Iiwi5Y-R6KGo5paH56ugIiwi5Y-R6KGo6K-E6K66Il0sImp0aSI6ImQ1ODM5OWFjLTI4OTEtNGE0ZC1hNThjLWQwZjNmN2JlNmRiNSIsImNsaWVudF9pZCI6InN0YXJCbG9nIn0.6PbINedMrvMUumPb5nvT0dzpzXr8fB86tENzsb8cT38


### 密码模式实测
POST localhost:9000/service-user/oauth/token?client_id=starBlog&client_secret=030321liuxinyu&grant_type=password&username={"account":"2064989403","authType":"password","password":"030321"}
